// src/data/products.js
export const PRODUCT_TYPES = [
  "Study Notes",
  "Cheat Sheets",
  "Collections",
  "Templates",
];

export const CATEGORIES = [
  "All",
  "SSC",
  "Python",
  "CBZ",
  "Web Dev",
  "Interview",
  "Productivity",
];

export const DIFFICULTY = ["All", "Beginner", "Intermediate", "Advanced"];

export const products = [
  {
    id: "notes-cbz-sem6-endocrinology",
    title: "CBZ Sem 6 — General Endocrinology Notes",
    type: "Study Notes",
    category: "CBZ",
    difficulty: "Intermediate",
    tags: ["CBZ", "Zoology", "Sem 6"],
    description: "Simple, exam-ready notes with key diagrams and important points.",
    pdf: "https://web.stanford.edu/class/cs142/lectures/ReactJS.pdf",
    price: 0,
    rating: 4.7,
    downloads: 1240,
    preview: [
      "Complete unit summary",
      "Important hormones & functions",
      "Short notes + long answers structure",
    ],
    whatsInside: [
      "Chapter-wise handwritten-style notes",
      "Important MCQs + short questions",
      "Revision pointers (1-page recap per unit)",
    ],
  },
  {
    id: "cheats-python-basics",
    title: "Python Basics Cheat Sheet",
    type: "Cheat Sheets",
    category: "Python",
    difficulty: "Beginner",
    tags: ["Python", "Basics", "Quick Revision"],
    description: "Syntax, loops, functions, list/dict tricks — fast revision sheet.",
    pdf: "https://web.stanford.edu/class/cs142/lectures/ReactJS.pdf",
    price: 49,
    rating: 4.8,
    downloads: 3320,
    preview: ["Top 50 syntax snippets", "Common mistakes", "Short examples"],
    whatsInside: ["PDF + printable format", "Mini practice set", "Cheat codes for interviews"],
  },
  {
    id: "collection-ssc-english-7days",
    title: "SSC English — 7 Day Revision Collection",
    type: "Collections",
    category: "SSC",
    difficulty: "Beginner",
    tags: ["SSC", "English", "7 Days"],
    description: "A 7-day plan with notes + daily quiz + flashcards.",
    pdf: "https://web.stanford.edu/class/cs142/lectures/ReactJS.pdf",
    price: 199,
    rating: 4.6,
    downloads: 980,
    featured: true,
    preview: ["Daily plan", "Grammar rules", "Quiz + flashcards"],
    whatsInside: ["7-day schedule", "Daily quiz sets", "Key grammar notes", "Vocabulary flashcards"],
  },
  {
    id: "template-resume-ats",
    title: "ATS Friendly Resume Template (One Page)",
    type: "Templates",
    category: "Interview",
    difficulty: "Beginner",
    tags: ["Resume", "ATS", "Job"],
    description: "Clean ATS resume template with sections + project bullets format.",
    pdf: "https://web.stanford.edu/class/cs142/lectures/ReactJS.pdf",
    price: 99,
    rating: 4.5,
    downloads: 2100,
    preview: ["ATS layout", "Project bullets", "Skills sections"],
    whatsInside: ["DOCX + Google Docs format", "Example bullets", "Checklist for freshers"],
  },
  {
    id: "notes-ssc-current-affairs-weekly",
    title: "Weekly Current Affairs Capsule",
    type: "Study Notes",
    category: "SSC",
    difficulty: "Beginner",
    tags: ["Current Affairs", "Weekly", "GK"],
    description: "2–3 important weekly topics with short Q/A for revision.",
    pdf: "https://web.stanford.edu/class/cs142/lectures/ReactJS.pdf",
    price: 0,
    rating: 4.4,
    downloads: 4500,
    preview: ["Weekly summary", "MCQ set", "Flashcards-ready points"],
    whatsInside: ["Short notes", "PYQ style questions", "Weekly quiz"],
  },
  {
    id: "collection-webdev-react-starter",
    title: "React Starter Collection",
    type: "Collections",
    category: "Web Dev",
    difficulty: "Intermediate",
    tags: ["React", "Hooks", "Projects"],
    description: "Notes + cheat sheets + mini projects checklist.",
    pdf: "https://web.stanford.edu/class/cs142/lectures/ReactJS.pdf",
    price: 299,
    rating: 4.7,
    downloads: 640,
    featured: true,
    preview: ["Hooks guide", "Component patterns", "Project roadmap"],
    whatsInside: ["React notes", "Hooks cheat sheet", "3 mini project briefs"],
  },
];
